### ISSUE TITLE
Does the "Planetbase Mod Patcher 2" work? 

### ISSUE THREAD

**Issue by NeoRider7** [solidDoWant/Planetbase-Framework#13]
On the NexusMods site, I found a mention of "[Planetbase Mod Patcher 2](https://www.nexusmods.com/planetbase/mods/35)". It says that that Patcher-2 created and downloaded solidDoWant, that is, you.

In the "[POSTS](https://www.nexusmods.com/planetbase/mods/35?tab=posts)", "[FORUM](https://www.nexusmods.com/planetbase/mods/35?tab=forum)", and "[BUGS](https://www.nexusmods.com/planetbase/mods/35?tab=bugs)" tabs, players write a lot of comments that mods do not work with this Patcher-2.

In this regard, the question is:

1. "[Planetbase Mod Patcher 2](https://www.nexusmods.com/planetbase/mods/35)" works or not?
1.1. If it works, please tell us how to use it so that the mods work.
1.2. Do [mods from JPFarias](https://www.nexusmods.com/users/19987409?tab=user+files) work with this Patcher-2?
Or maybe some other mods are needed for Patcher-2?

2. Could you answer, with at least one answer, the many questions on NexusMods in the [POSTS](https://www.nexusmods.com/planetbase/mods/35?tab=posts), [FORUM](https://www.nexusmods.com/planetbase/mods/35?tab=forum), and [BUGS](https://www.nexusmods.com/planetbase/mods/35?tab=bugs) tabs?

So many players want to clear things up with "Planetbase Mod Patcher 2"!
Thanks a lot!

**Comment by solidDoWant** [comment]
1. Yes it does work, and that is the latest release
    1.1/2 The patcher/framework is not compatible with JPFaires' mods, so none of the mods he wrote (especially any relying on his Redirector mod) will work with it
2. I'll reply if I get some time in the next couple of days. The short of it is, JPFaires' mods do not work with my framework/patcher. My framework has significant improvements over his (on the fly building support, on the fly memory patching via Harmony, only a single hook into the base game code, stability improvements, etc.), but also has had significantly fewer mods written for it. Users need to pick one, not both. Regarding the virus/virustotal thing, I have that pop up periodically. [See here for details](https://github.com/solidDoWant/Planetbase-Framework/issues/6). It's a false positive, and users can verify this by reviewing the code/compiling it themselves and testing if they like.
