### ISSUE TITLE
Contact info on the wiki is outdated

### ISSUE THREAD

**Issue by Tahvohck** [solidDoWant/Planetbase-Framework#14]
I was trying to hit you up on Discord about the framework, specifically about some of my own work that I've done in the modding scene, but your contact info for Discord is outdated. Can you update that, or shoot me your user tag?

**Comment by solidDoWant** [comment]
Updated (https://discord.gg/EW47zVn). My user tag is currently `My Dude, I Am Here#8280` if you want to message me directly as well.
