### ISSUE TITLE
Unable To Build From Master

### ISSUE THREAD

**Issue by tparikka** [solidDoWant/Planetbase-Framework#7]
I forked and built and ran into two issues when trying to build:

1. The function loadPrefab in BaseModuleType.cs is marked override but the base type function inherited from ModuleType cannot be overridden because it's not marked virtual, abstract, or override.
2. In loadPrefab, there is a call to calculateSmoothMeshRecursive passing in "mMeshes" which is an object that doesn't seem to exist.

I'm building on a Windows 10 Pro instance in VS 2017 Enterprise.

**Comment by solidDoWant** [comment]
Did you patch the game first?

**Comment by tparikka** [comment]
I apologize if I missed something, I'm a new-ish dev. I'm trying to build, following your suggestion in #6. However I'm unable build the actual solution (from the master branch) because of the two issues above. My expectation was that I would fork the repo, build the solution and use the build artifacts to patch the game.

**Comment by solidDoWant** [comment]
I see the issue - you want this project: https://github.com/solidDoWant/Planetbase-Modpatcher. The patcher is what's uploaded to the mod nexus, and is what Windows Defender is currently flagging as a trojan. You should be able to build the patcher without issues. 

The patcher changes some of the properties of fields and classes to allow, and injects a call to the framework.  The framework (this project) is a library for loading and updating mods, as well as providing a library of classes and utilities for building mods.

**Comment by tparikka** [comment]
Ah. That would do it. Thanks for the clarification!
